version: "3"
services:
  rundeck:
    image: rundeck/rundeck:4.6.1
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
    tty: true
    volumes:
      - ./.docker/data/rundeck:/home/rundeck/server/data
      - ./.docker/configs/rundeck/remco/templates/rundeck-config.properties:/etc/remco/templates/rundeck-config.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4440"]
      interval: 30s
      timeout: 10s
      retries: 5
  rundeck_exporter:
    build: .
    ports:
      - 9622:9622
    environment:
      RUNDECK_URL: "http://rundeck:4440"
      RUNDECK_TOKEN: "k6nz3bEMAUt9hfaQvnosjpOoVP2czGYJ"
      RUNDECK_API_VERSION: 40
    depends_on:
      rundeck:
        condition: service_healthy
    links:
      - rundeck
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./.docker/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.docker/data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    links:
      - rundeck_exporter
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./.docker/data/grafana:/var/lib/grafana
      - ./.docker/configs/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    links:
      - prometheus
