apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  version: 1
  orgId: 1
  url: http://prometheus:9090
  access: proxy
  isDefault: true
  editable: true